### ISSUE TITLE
Identify Documentation Team Owner

### ISSUE THREAD

**Issue by clorton** [InstituteforDiseaseModeling/pycms#4]
Allows us to check off "Identify documentation team owner" in the [PBW checklist](https://wiki.idmod.org/display/SP/PyCMS+-+Python+Package+Exposing+CMS+Functionality)

**Comment by MIzzo-IDM** [comment]
@JSchripsema-IDM, would you like to be the owner or would you like me to do it? :-)

**Comment by JSchripsema-IDM** [comment]
@MIzzo-IDM I'm happy to own it! :)

**Comment by MIzzo-IDM** [comment]
Ok sweet! All yours ;-)
