### ISSUE TITLE
Create Project 1-Pager

### ISSUE THREAD

**Issue by clorton** [InstituteforDiseaseModeling/pycms#8]
Allows us to check off "Create lo-fi project specification" in the [PBW checklist](https://wiki.idmod.org/display/SP/PyCMS+-+Python+Package+Exposing+CMS+Functionality)

**Comment by JProctor-IDM** [comment]
[ProjectPythonStochasticSims.docx](https://github.com/InstituteforDiseaseModeling/pycms/files/4822533/ProjectPythonStochasticSims.docx)

**Comment by clorton** [comment]
Resolved with 66562f6.
